name: Build and Deploy Docker Image to VPS

runs-on: self-hosted

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_NAME: website
  PROJECT_DIR: ~/projects/website
  DOCKER_DIR: docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ env.PROJECT_NAME }} .

      - name: Export Docker image as tar
        run: |
          mkdir -p ${{ env.DOCKER_DIR }}
          docker save ${{ env.PROJECT_NAME }} -o ${{ env.DOCKER_DIR }}/${{ env.PROJECT_NAME }}.tar

      - name: Clean old tar on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "${{ secrets.VPS_HOST }}"
          username: "${{ secrets.VPS_USER }}"
          key: "${{ secrets.VPS_SSH_KEY }}"
          port: "${{ secrets.VPS_PORT }}"
          script: |
            rm -rf ${{ env.PROJECT_DIR }}/${{ env.DOCKER_DIR }}/${{ env.PROJECT_NAME }}.tar

      - name: Copy image to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "${{ secrets.VPS_HOST }}"
          username: "${{ secrets.VPS_USER }}"
          key: "${{ secrets.VPS_SSH_KEY }}"
          port: "${{ secrets.VPS_PORT }}"
          source: "${{ env.DOCKER_DIR }}/${{ env.PROJECT_NAME }}.tar"
          target: "${{ env.PROJECT_DIR }}/"

      - name: Load and run image on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "${{ secrets.VPS_HOST }}"
          username: "${{ secrets.VPS_USER }}"
          key: "${{ secrets.VPS_SSH_KEY }}"
          port: "${{ secrets.VPS_PORT }}"
          script: |
            cd ${{ env.PROJECT_DIR }}/${{ env.DOCKER_DIR }}
            docker load -i ${{ env.PROJECT_NAME }}.tar

            echo "🧹 Stopping and removing existing container (if any)..."
            docker stop ${{ env.PROJECT_NAME }} || true
            docker rm ${{ env.PROJECT_NAME }} || true

            echo "🚀 Running new container..."
            docker run -d --name ${{ env.PROJECT_NAME }} -p 80:80 \
              -v ${{ env.PROJECT_DIR }}/videos:/usr/local/apache2/htdocs/videos \
              ${{ env.PROJECT_NAME }}

            echo "✅ Deployed successfully"
